// jirengu/course-projects/echarts-demo-1/src/vue-echarts.vue
<template>
  <div ref="container">
  </div>
</template>

<script>
  import echarts from 'echarts'
  export default {
    props: ['option', 'loading'],
    mounted() {
      const width = document.documentElement.clientWidth
      this.$refs.container.style.width = `${width - 20}px`
      this.$refs.container.style.height = `${(width - 20) * 1.2}px`
      this.chart = echarts.init(this.$refs.container, 'dark')
      this.chart.setOption(this.option)
    },
    watch: {
      option() {
        console.log(this.option)
        this.chart.setOption(this.option)
      },
      loading() {
        if (this.loading) {
          this.chart.showLoading()
        } else {
          this.chart.hideLoading()
        }
      }
    }
  }
</script>

// jirengu/course-projects/echarts-demo-1/src/react-echarts.jsx
import React from 'react'
import echarts from 'echarts'

export function ReactEcharts(props) {
  const {option, loading} = props
  const container = React.useRef(null)
  const chart = React.useRef(null)
  React.useEffect(() => {
    const width = document.documentElement.clientWidth
    container.current.style.width = `${width - 20}px`
    container.current.style.height = `${(width - 20) * 1.2}px`
    chart.current = echarts.init(container.current, 'dark')
  }, [])
  React.useEffect(() => {
    chart.current.setOption(option)
  }, [option])
  React.useEffect(() => {
    if (loading) {
      chart.current.showLoading()
    } else {
      chart.current.hideLoading()
    }

  }, [loading])
  return (
    <div ref={container}/>
  )
}
