// jirengu/react-epic/src/components/Footer.js
import React from 'react'
import styled from 'styled-components'

const Footer = styled.footer`
  padding: 10px 100px;
  text-align: center;
  font-size: 12px;
  color: #aaa;
`

function Component () {
  return (
    <Footer>
      <h1>Footer</h1>
    </Footer>
  )
}

export default Component

// jirengu/share-blog/src/components/Footer.vue
<template>
  <footer>
    <p>© share-blog 2020</p>
  </footer>
</template>

<script>
export default {
  name: 'Footer'
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
footer {
  align-self: end;
  background-color: #d7d7d7;
  color: #666;
  font-size: 13px;
  padding: 10px;
  text-align: center;
}
</style>
