// jirengu/second-stage/course-projects/echarts-basic/echarts-demo-4/src/Echarts.jsx
import React, { useEffect, useRef } from "react";
import * as echarts from "echarts";

export function Echarts(props) {
  const { option, loading } = props;
  const container = useRef(null);
  const chart = useRef(null);

  useEffect(() => {
    const width = document.documentElement.clientWidth;
    container.current.style.width = `${width - 20}px`;
    container.current.style.height = `${(width - 20) * 1.2}px`;
    chart.current = echarts.init(container.current, "dark");
  }, []);

  useEffect(() => {
    chart.current.setOption(option);
  }, [option]);

  useEffect(() => {
    if (loading) {
      chart.current.showLoading();
    } else {
      chart.current.hideLoading();
    }
  }, [loading])

  return <div ref={container}></div>;
}

// jirengu/second-stage/course-projects/echarts-basic/echarts-demo-3/src/echarts.vue
<template>
  <div ref="container"></div>
</template>

<script>
import * as echarts from "echarts";

export default {
  props: {
    option: {
      type: Object,
      default: () => ({}),
    },
    loading: {
      type: Boolean,
      default: false,
    },
  },
  mounted() {
    const width = document.documentElement.clientWidth;
    this.$refs.container.style.width = `${width - 20}px`;
    this.$refs.container.style.height = `${(width - 20) * 1.2}px`;
    this.chart = echarts.init(this.$refs.container, 'dark');
    this.chart.setOption(this.option);
  },
  watch: {
    option: {
      handler(newOption) {
        this.chart.setOption(newOption);
      },
      deep: true,
    },
    loading: {
      handler(newLoading) {
        if (newLoading) {
          this.chart.showLoading();
        } else {
          this.chart.hideLoading();
        }
      },
    }
  }
};
</script>
